-- =====================================================================
-- pg COMMENTS — R2 (B2B OKK)
-- Generated by scripts/generate-pg-comments.ts (do NOT hand-edit).
-- Source: docs/DASHBOARD-*.md (Источники данных) + src/lib/db/schema-*.ts.
-- Apply via Neon SQL editor (HTTP timeout-safe). Idempotent.
-- =====================================================================

BEGIN;

-- ─── public._backup_calls_20260429 ───
COMMENT ON TABLE public._backup_calls_20260429 IS '[R2 / B2B OKK] [BACKUP — заморозка 2026-04-29 перед mass re-eval] НЕ ИСПОЛЬЗОВАТЬ для аналитики; используй public.calls.';

-- ─── public._backup_managers_20260429 ───
COMMENT ON TABLE public._backup_managers_20260429 IS '[R2 / B2B OKK] [BACKUP — заморозка 2026-04-29] НЕ ИСПОЛЬЗОВАТЬ; используй public.managers.';

-- ─── public.calls ───
COMMENT ON TABLE public.calls IS '[R2 / B2B OKK] Источник звонка (запись, транскрипт, направление, длительность, Kommo-связи). Used by tabs: Аналитика, Дейли, ОКК.';
COMMENT ON COLUMN public.calls.manager_id IS 'FK → managers.id (UUID, OKK-локальный). NULL → orphan; UI/MCP такие звонки скрывают.';
COMMENT ON COLUMN public.calls.contact_phone IS 'PII: телефон контакта. MCP маскирует до ''+7***1234'' независимо от роли (см. utils/pii.ts когда landed).';
COMMENT ON COLUMN public.calls.duration_seconds IS 'Длительность звонка. Только evaluated calls с длительностью ≥10s попадают в OKK; короткие фильтруются.';
COMMENT ON COLUMN public.calls.direction IS '''inbound'' | ''outbound''. Драйвит speaker labelling: outbound → Speaker A = клиент; inbound → Speaker A = менеджер. NULL → raw labels.';
COMMENT ON COLUMN public.calls.transcript_speakers IS 'JSONB массив сегментов { speaker, text, start, end }. NULL на старых звонках — UI fall-back на plain transcript.';
COMMENT ON COLUMN public.calls.kommo_lead_id IS 'Kommo lead.id. JOIN-ключ в analytics.leads_cohort.lead_id и tracking_events.entity_id (entity_type=''lead''). NULL → звонок не привязан к лиду (orphan, UI скрывает).';
COMMENT ON COLUMN public.calls.kommo_lead_url IS 'Полный URL лида в Kommo. Используется UI для deep-link.';
COMMENT ON COLUMN public.calls.status IS '''pending'' | ''evaluated'' | ''error''. UI/MCP показывают только evaluated.';

-- ─── public.evaluations ───
COMMENT ON TABLE public.evaluations IS '[R2 / B2B OKK] AI-оценка звонка с разбиением по блокам и критериям. Used by tabs: Аналитика, Аудит, ОКК.';
COMMENT ON COLUMN public.evaluations.call_id IS 'FK → calls.id. 1:1 — один evaluation на звонок.';
COMMENT ON COLUMN public.evaluations.manager_id IS 'FK → managers.id. Дублирует calls.manager_id для прямых per-manager агрегаций без JOIN.';
COMMENT ON COLUMN public.evaluations.prompt_type IS 'Тип промпта (определяет каноничный набор блоков/критериев). Используется Аналитикой для группировки.';
COMMENT ON COLUMN public.evaluations.total_score IS 'Итоговый балл оценки (0-100). NULL → оценка не завершена; UI/MCP такие звонки прячут.';
COMMENT ON COLUMN public.evaluations.evaluation_json IS 'Полная структура оценки: { blocks[], total_score, total_max_score, summary, client_scoring }. Каждый block: { name, score|block_score, max_score|max_block_score, criteria[] }, каждый criterion: { name, score, max_score, feedback, quote? }. Поддерживает legacy (score/max_score) и новый (block_score/max_block_score) форматы.';
COMMENT ON COLUMN public.evaluations.call_number IS 'Порядковый номер звонка менеджера в этой OKK-БД (D1, D2, ...) — не FK, локальный счётчик OKK.';
COMMENT ON COLUMN public.evaluations.override_metadata IS 'JSON метаданные программных корректировок AI-оценки. Ключи: is_followup, followup_signal_source (lead_id|phone_fallback|phone_fallback_no_crm|null), prior_count, call_type (primary|followup|interrupted|unqualified|transfer|deferred_start|unknown), overrides_applied (массив правил), score_before_override, score_after_override.';

-- ─── public.managers ───
COMMENT ON TABLE public.managers IS '[R2 / B2B OKK] Имя/линия/команда менеджера для фильтра и подписи. Used by tabs: Аналитика, ОКК.';
COMMENT ON COLUMN public.managers.role IS '''manager'' | ''rop'' | ''admin''. В B2B нет line, поэтому double-status (rop+line) тут не применяется — ROP это всегда не-линейный.';
COMMENT ON COLUMN public.managers.line IS 'B2B не использует line-конвенцию — всегда NULL. (В D2 значение драйвит B2G линии 1=квалификатор, 2=бератер, 3=доведение.)';
COMMENT ON COLUMN public.managers.is_active IS 'Soft-delete (синкается из master_managers.is_active).';
COMMENT ON COLUMN public.managers.kommo_user_id IS 'Kommo user ID. Резолвится из master_managers.kommo_user_id при синке.';

-- ─── public.phantom_history ───
COMMENT ON TABLE public.phantom_history IS '[R2 / B2B OKK] Дневной аггрегат покрытия webhook''ом телефонии. Used by tabs: Аудит.';
COMMENT ON COLUMN public.phantom_history.date IS 'Civil-date в Europe/Berlin. PK (department, manager_id, date).';
COMMENT ON COLUMN public.phantom_history.phantom_count IS 'Кол-во CDR-звонков, не попавших в OKK (= не оценённых, например короткие <10s).';
COMMENT ON COLUMN public.phantom_history.coverage_pct IS '% звонков менеджера из telephony_cdr, которые попали в OKK calls на этот день. Heatmap в Аудит-tab.';

-- ─── public.telephony_cdr ───
COMMENT ON TABLE public.telephony_cdr IS '[R2 / B2B OKK] [INTERNAL — OKK] Phase 2 webhook coverage tracking: сырой CDR для proof-of-coverage. Источник для phantom_history. Не для прямых запросов.';
COMMENT ON COLUMN public.telephony_cdr.department IS '''b2g'' | ''b2b''.';
COMMENT ON COLUMN public.telephony_cdr.telephony IS '''callgear'' | ''cloudtalk'' — провайдер CDR.';
COMMENT ON COLUMN public.telephony_cdr.external_call_id IS 'ID звонка в провайдере. Combined с telephony provides global uniqueness.';
COMMENT ON COLUMN public.telephony_cdr.call_started_at IS 'Время начала звонка (UTC).';
COMMENT ON COLUMN public.telephony_cdr.direction IS '''in'' | ''out'' (CDR-уровень, до Kommo).';
COMMENT ON COLUMN public.telephony_cdr.is_in_okk IS 'true → CDR попал в OKK calls (был оценён). false → phantom (короткий <10s или filtered).';
COMMENT ON COLUMN public.telephony_cdr.okk_call_id IS 'FK → calls.id когда is_in_okk=true. NULL для phantom.';

-- ─── public.voice_feedback ───
COMMENT ON TABLE public.voice_feedback IS '[R2 / B2B OKK] Голосовой ответ менеджера на оценку (если был). Used by tabs: ОКК.';
COMMENT ON COLUMN public.voice_feedback.call_id IS 'FK → calls.id. К какому звонку относится голос-ответ менеджера.';
COMMENT ON COLUMN public.voice_feedback.manager_id IS 'FK → managers.id (который ответил).';
COMMENT ON COLUMN public.voice_feedback.voice_file_id IS 'ID файла в Telegram storage (file_id для resend).';
COMMENT ON COLUMN public.voice_feedback.transcript IS '[PII] Транскрипт голос-ответа менеджера. MCP tools НЕ возвращают этот текст — приватный feedback.';
COMMENT ON COLUMN public.voice_feedback.ai_response IS 'AI-парафраз ответа (если был сгенерирован). Может быть менее sensitive чем raw transcript.';

-- ─── public.worst_calls ───
COMMENT ON TABLE public.worst_calls IS '[R2 / B2B OKK] Топ-N худших звонков менеджера за день/период. Drives WorstCallsPanel popup в ОКК-разделе + Telegram-уведомления (14:00/17:00). FK: call_id → calls.id, evaluation_id → evaluations.id, manager_id → managers.id.';
COMMENT ON COLUMN public.worst_calls.call_id IS 'FK → calls.id. Какой именно звонок попал в топ-N худших.';
COMMENT ON COLUMN public.worst_calls.evaluation_id IS 'FK → evaluations.id (snapshot оценки на момент включения в worst).';
COMMENT ON COLUMN public.worst_calls.period IS '''morning'' | ''afternoon'' — слот уведомления (14:00 / 17:00 Europe/Berlin).';
COMMENT ON COLUMN public.worst_calls.responded IS 'Менеджер ответил голосом на уведомление. Драйвит response_adequate (после Grok adequacy check).';

COMMIT;
