-- =====================================================================
-- pg COMMENTS — D2 (B2G OKK)
-- Generated by scripts/generate-pg-comments.ts (do NOT hand-edit).
-- Source: docs/DASHBOARD-*.md (Источники данных) + src/lib/db/schema-*.ts.
-- Apply via Neon SQL editor (HTTP timeout-safe). Idempotent.
-- =====================================================================

BEGIN;

-- ─── public.calls ───
COMMENT ON TABLE public.calls IS 'Источник звонка (запись, транскрипт, направление, длительность, Kommo-связи). Used by tabs: Аналитика, Дейли, ОКК.';
COMMENT ON COLUMN public.calls.contact_phone IS 'PII: телефон контакта. MCP маскирует до ''+7***1234'' независимо от роли (см. utils/pii.ts когда landed).';
COMMENT ON COLUMN public.calls.direction IS '''inbound'' | ''outbound''. Драйвит speaker labelling: outbound → Speaker A = клиент; inbound → Speaker A = менеджер. NULL → raw labels.';
COMMENT ON COLUMN public.calls.transcript_speakers IS 'JSONB массив сегментов { speaker, text, start, end }. NULL на старых звонках — UI fall-back на plain transcript.';
COMMENT ON COLUMN public.calls.kommo_lead_url IS 'Полный URL лида в Kommo. Используется UI для deep-link.';
COMMENT ON COLUMN public.calls.status IS '''pending'' | ''evaluated'' | ''error''. UI/MCP показывают только evaluated.';

-- ─── public.evaluations ───
COMMENT ON TABLE public.evaluations IS 'Оценка с разбивкой по блокам/критериям. Used by tabs: Аналитика, Аудит, ОКК.';
COMMENT ON COLUMN public.evaluations.prompt_type IS 'Тип промпта (определяет каноничный набор блоков/критериев). Используется Аналитикой для группировки.';
COMMENT ON COLUMN public.evaluations.total_score IS 'Итоговый балл оценки (0-100). NULL → оценка не завершена; UI/MCP такие звонки прячут.';
COMMENT ON COLUMN public.evaluations.evaluation_json IS 'Полная структура оценки: { blocks[], total_score, total_max_score, summary, client_scoring }. Каждый block: { name, score|block_score, max_score|max_block_score, criteria[] }, каждый criterion: { name, score, max_score, feedback, quote? }. Поддерживает legacy (score/max_score) и новый (block_score/max_block_score) форматы.';
COMMENT ON COLUMN public.evaluations.call_number IS 'Порядковый номер звонка менеджера в этой OKK-БД (D1, D2, ...) — не FK, локальный счётчик OKK.';
COMMENT ON COLUMN public.evaluations.override_metadata IS 'JSON метаданные программных корректировок AI-оценки. Ключи: is_followup, followup_signal_source (lead_id|phone_fallback|phone_fallback_no_crm|null), prior_count, call_type (primary|followup|interrupted|unqualified|transfer|deferred_start|unknown), overrides_applied (массив правил), score_before_override, score_after_override.';

-- ─── public.managers ───
COMMENT ON TABLE public.managers IS 'Имя/линия/команда менеджера для фильтра и подписи. Used by tabs: Аналитика, ОКК.';
COMMENT ON COLUMN public.managers.role IS '''manager'' | ''rop'' | ''admin''. ROP с непустой line — линейный сотрудник.';
COMMENT ON COLUMN public.managers.line IS 'B2G линия: ''1''=квалификатор, ''2''=бератер, ''3''=доведение. ROP с непустой line — double-status, включается как линейный.';
COMMENT ON COLUMN public.managers.is_active IS 'Soft-delete (синкается из master_managers.is_active).';

-- ─── public.phantom_history ───
COMMENT ON TABLE public.phantom_history IS 'Дневной аггрегат покрытия webhook''ом телефонии. Used by tabs: Аудит.';
COMMENT ON COLUMN public.phantom_history.phantom_count IS 'Кол-во CDR-звонков, не попавших в OKK (= не оценённых, например короткие <10s).';
COMMENT ON COLUMN public.phantom_history.coverage_pct IS '% звонков менеджера из telephony_cdr, которые попали в OKK calls на этот день. Heatmap в Аудит-tab.';

-- ─── public.telephony_cdr ───
COMMENT ON TABLE public.telephony_cdr IS '[INTERNAL — OKK] Phase 2 webhook coverage tracking: сырой CDR для proof-of-coverage. Источник для phantom_history. Не для прямых запросов.';

-- ─── public.voice_feedback ───
COMMENT ON TABLE public.voice_feedback IS 'Голосовой ответ менеджера на оценку (если был). Used by tabs: ОКК.';

-- ─── public.worst_calls ───
COMMENT ON TABLE public.worst_calls IS 'Топ-N худших звонков менеджера за день/период. Drives WorstCallsPanel popup в ОКК-разделе + Telegram-уведомления (14:00/17:00). Связан с calls/evaluations/voice_feedback по FK.';

COMMIT;
